
import type { User, Credentials, Appointment, ThemeSettings } from '@/types'; 

export const USER_ROLES = {
  ADMIN: 'Admin',
  MAYOR: 'Prefeito',
  VICE_MAYOR: 'Vice-prefeito',
  VIEWER: 'Visualizador',
} as const;

export const LOCAL_STORAGE_KEYS = {
  LOGGED_IN_USER: 'agendaGovUser',
  USERS: 'agendaGovUsers',
  APPOINTMENTS: 'agendaGovAppointments',
  THEME_SETTINGS: 'agendaGovThemeSettings',
};

export const DEFAULT_LOGO_URL = "https://pmsantoangelo.abase.com.br/site/Brasoes/120/cabecalho.png";

export const DEFAULT_THEME_SETTINGS: ThemeSettings = {
  appName: 'AgendaGov',
  colors: {
    background: "#ECEFF1", 
    foreground: "#383A3D", 
    card: "#FFFFFF",       
    cardForeground: "#383A3D", 
    popover: "#FFFFFF",      
    popoverForeground: "#383A3D", 
    primary: "#3F51B5",      
    primaryForeground: "#FFFFFF", 
    secondary: "#E0E5E9",    
    secondaryForeground: "#383A3D", 
    muted: "#E0E5E9",        
    mutedForeground: "#696E75", 
    accent: "#9575CD",       
    accentForeground: "#FFFFFF", 
    destructive: "#F44336",  
    destructiveForeground: "#FAFAFA", 
    border: "#D3D7DB",       
    input: "#D3D7DB",        
    ring: "#3F51B5",         
    sidebarBackground: "#2B303B",       
    sidebarForeground: "#F9FAFC",       
    sidebarPrimary: "#3F51B5",          
    sidebarPrimaryForeground: "#FFFFFF", 
    sidebarAccent: "#3C4352",           
    sidebarAccentForeground: "#F9FAFC",  
    sidebarBorder: "#1F2329",           
    sidebarRing: "#3F51B5",             
  },
  logoLightModeUrl: DEFAULT_LOGO_URL,
  logoDarkModeUrl: DEFAULT_LOGO_URL,
};


export const DEFAULT_USERS_CREDENTIALS: Array<User & { password?: string }> = [
  { id: 'user-admin', username: 'admin', password: 'crm123', name: 'Administrador', role: USER_ROLES.ADMIN },
  { id: 'user-prefeito', username: 'prefeito', password: 'crm123', name: 'Prefeito João Silva', role: USER_ROLES.MAYOR },
  { id: 'user-vice', username: 'vice', password: 'crm123', name: 'Vice-Prefeita Maria Costa', role: USER_ROLES.VICE_MAYOR },
  {
    id: 'user-viewer',
    username: 'viewer',
    password: 'crm123',
    name: 'Assessor de Gabinete',
    role: USER_ROLES.VIEWER,
    canViewCalendarsOf: ['user-prefeito'], 
  },
];

const PREFEITO_USER_ID = 'user-prefeito';

export const INITIAL_APPOINTMENTS: Omit<Appointment, 'id' | 'createdAt'>[] = [
  {
    title: 'REUNIÃO DE ALINHAMENTO COM TODOS OS SECRETÁRIOS',
    date: '2025-04-30',
    time: '08:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'Gabinete',
    notes: '',
    contactPerson: '',
    participants: 'Todos Scretários',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'POSSE DO NÚCLEO DO BAIRRO SÃO JOÃO',
    date: '2025-04-30',
    time: '14:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'Bairro São João',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM O SECRETÁRIO CLEBERSON',
    date: '2025-04-30',
    time: '15:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'Gabinete',
    notes: '',
    contactPerson: '',
    participants: 'Cleberson Taborda',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM RODRIGO FLORES E ANDRÉ RUSCHEL',
    date: '2025-04-30',
    time: '16:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'Gabinete do Vice-Prefeito',
    notes: '',
    contactPerson: '55997000995',
    participants: 'Rodrigo Flores, Carlos Gonçalves, Rolando Burgel, André Ruschel',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'Live com o secretário Cleberson',
    date: '2025-04-30',
    time: '19:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'Gabinete',
    notes: '',
    contactPerson: '',
    participants: 'Cleberson',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'CÂMARA DE VEREADORES SOBRE OS 400 ANOS DAS MISSÕES',
    date: '2025-05-02',
    time: '09:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'R. Antunes Ribas, 1111 - Centro, Santo Ângelo - RS, 98801-630',
    notes: '',
    contactPerson: '',
    participants: 'Vereadores, Sec.Turismo/Vinicius Makvitiz. Sr. Carlos Gonçalves participou.',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'Visita na Unimed logo após janta com Dr Madureira e Tiago da UPA',
    date: '2025-05-02',
    time: '16:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'Av. Getúlio Vargas, 1079 - Missões, Santo Ângelo - RS, 98801-703',
    notes: '',
    contactPerson: '',
    participants: 'Dr. Madureira e Tiago UPA',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'LIVE CANCELADA',
    date: '2025-05-02',
    time: '19:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'Gabinete',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: false, // Status 'Não Realizado' maps to false
  },
  {
    title: 'MISSA NA CATEDRAL',
    date: '2025-05-03',
    time: '15:30',
    assignedTo: PREFEITO_USER_ID,
    location: 'Praça Pinheiro Machado',
    notes: '',
    contactPerson: '',
    participants: 'Vinícius Makivitz',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'ALMOÇO NO LAGEADO MICUIM',
    date: '2025-05-04',
    time: '12:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'Lajeado Micuim',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'REUNIÃO C/LEANDRA-RH E MARISA/SINDICATO FUNCIONÁRIOS MUNICIPAIS, REF. IPE',
    date: '2025-05-05',
    time: '08:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'no GAB',
    notes: '',
    contactPerson: '',
    participants: 'Srª. Leandra/RH; Srª. Marisa/Sindicato; Sr. Nívio/Prefeito',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO C/PRODUTOR RURAL, FRANCISCO E CULTURA.',
    date: '2025-05-06',
    time: '08:30',
    assignedTo: PREFEITO_USER_ID,
    location: 'no GAB',
    notes: '',
    contactPerson: '',
    participants: 'Sr. Nívio; Sr. Carlos Gonçalves; Cleberson; Edimilson e Assessor; Vinicius e Cris.',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO DE ALINHAMENTO C/VEREADORES',
    date: '2025-05-05',
    time: '10:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'no GAB',
    notes: '',
    contactPerson: '',
    participants: 'Prefeito; Vice-Prefeito; Chefe de Gabinete e Vereadores',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIAO AMM',
    date: '2025-05-05',
    time: '14:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'Em Cerro Largo',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: false, // Status 'Não Realizado' maps to false
  },
  {
    title: 'REUNIÃO C/ADV. NICO MARCHIONATTI',
    date: '2025-05-06',
    time: '14:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'no GAB',
    notes: '',
    contactPerson: '',
    participants: 'Sr. Nívio; Sr. Nico Marchionatti; Srª Rosimere/Sec. Assistência Social',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO C/VINICIUS MAKVITIZ E PESSOAL SISTEMA DE VIGILÂNCIA SANITÁRIA E DEPTO DE TRÂNSITO',
    date: '2025-05-06',
    time: '15:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'no GAB',
    notes: '',
    contactPerson: '',
    participants: 'Sec.Turismo/Sr. Vinicius Makvitz; Coord. Trânsito/Sr. Nelson Koch;',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'SOLENIDADE DE ABERTURA DO CAMPEONATO MUNICIPAL DE FUTEBOL AMADOR/2025-TROFÉU JARDEL AUGUSTO OBERMEIER',
    date: '2025-05-04',
    time: '13:30',
    assignedTo: PREFEITO_USER_ID,
    location: 'no Campo Municipal de Eventos Hélio Costa de Oliveira (antigo SESI).',
    notes: '',
    contactPerson: '',
    participants: 'Sr. Nívio; Edimilson.',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'VISITA DO COMANDANTE DOS BOMBEIROS/DEFESA CIVIL DO RS.',
    date: '2025-05-07',
    time: '10:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'no GAB',
    notes: '',
    contactPerson: '',
    participants: 'Sr. Nívio; Sr. Castanho; Sr. Carlos Kelm deverá providenciar um mimo p/entrega ao convidado.',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO C/SRª LEANDRA/RH E A SRª MARISA/SINDICATO DOS FUNCIONÁRIOS MUNICIPAIS, P/TRATAR SOBRE IPE E OUTROS ASSUNTOS DE INTERESSE DA CLASSE',
    date: '2025-05-05',
    time: '08:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'no GAB',
    notes: '',
    contactPerson: '',
    participants: 'Leandra/RH; Marisa/Sindicato Func. Municipais; Sr. Nívio',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM CARLÃO/ZAGUEIRO.',
    date: '2025-05-06',
    time: '11:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'no GAB',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM O RURAL, SOBRE PAA',
    date: '2025-05-06',
    time: '16:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'no GAB',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO C/SEC.EDUCAÇÃO-ANE E ADV.LUIS ANTONIO (PROFISSIONAL DE APOIO A ESTAGIÁRIO)',
    date: '2025-05-08',
    time: '08:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'no GAB',
    notes: '',
    contactPerson: '',
    participants: 'Sr. Nívio; Sec. Educação/Ane e Adv. Luiz Antônio',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'INAUGURAÇÃO DA FARMÁCIA SÃO JOÃO',
    date: '2025-05-10',
    time: '09:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'Antigo ARENA',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'AUDIÊNCIA REF. INQUÉRITO POLICIAL/ZONA ELEITORAL',
    date: '2025-05-12',
    time: '14:00',
    assignedTo: PREFEITO_USER_ID,
    location: '2ª V.CRIMINAL/FORUM (SL. 306-3º ANDAR),',
    notes: '',
    contactPerson: '',
    participants: 'Sr. Nívio; Márcio Zimpel; Rubia Ignes Rubi Schneider e Rolando Eduardo Esswein Burgel.',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO NO DETUR',
    date: '2025-05-13',
    time: '09:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'Cerro Largo (na Sede da Entidade)',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'SOLENIDADE DE INAUGURAÇÃO DA PISTA DE JULGAMENTO DE CAVALOS CRIOULOS',
    date: '2025-05-10',
    time: '11:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'nucleo missioneiro',
    notes: '',
    contactPerson: '',
    participants: 'vice Carlos Gonçalves',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM O PESSOAL DA CAIXA ECONOMICA FEDERAL DE PASSO FUNDO',
    date: '2025-05-13',
    time: '15:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'GABINETE',
    notes: '',
    contactPerson: '5421047981',
    participants: 'CARLOS GONÇALVES E CARLOS KELM',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO SEMANAL COM OS VEREADORES DA BASE',
    date: '2025-05-12',
    time: '10:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'GABINETE',
    notes: '',
    contactPerson: '',
    participants: 'Vereadores: Belmiro, Buiu; Toledo; Bispo',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'LIVE SOBRE A SAÚDE',
    date: '2025-05-09',
    time: '18:30',
    assignedTo: PREFEITO_USER_ID,
    location: 'GABINETE',
    notes: '',
    contactPerson: '',
    participants: 'secretário da saúde FLAVIO',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'LIVE SOCIAL',
    date: '2025-06-07',
    time: '18:30',
    assignedTo: PREFEITO_USER_ID,
    location: 'GABINETE',
    notes: '',
    contactPerson: '',
    participants: 'SECRETÁRIA ROSE',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'LIVE SOCIAL',
    date: '2025-05-07',
    time: '18:30',
    assignedTo: PREFEITO_USER_ID,
    location: 'GABINETE',
    notes: '',
    contactPerson: '',
    participants: 'SECRETÁRIA ROSE',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM JOÃO CARLOS GROS DE ALMEIDA SOBRE VALORES DE FUNDOS MUNICIPAIS',
    date: '2025-05-13',
    time: '16:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'GABINETE',
    notes: '',
    contactPerson: '',
    participants: 'CARLOS GONÇALVES',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM ALCIDES SCHIRMER SOBRE TERRENO NA MARECHAL FLORIANO QUE DA ACESSO AO FLORIPA',
    date: '2025-05-13',
    time: '17:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'NO GABINETE',
    notes: '',
    contactPerson: '',
    participants: 'CARLOS GONÇALVES',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM O SECRETARIO DA SAÚDE FLAVIO',
    date: '2025-05-09',
    time: '08:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'NO GABINETE',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM O COMANDANTE DA BRIGADA MILITAR SOBRE O MONITORAMENTO',
    date: '2025-05-12',
    time: '08:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'GABINETE',
    notes: '',
    contactPerson: '',
    participants: 'RODRIGO FLORES, ANDRÉ PEDROSO E CLEBER',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM SECRETÁRIO ANDRÉ PEDROSO',
    date: '2025-05-14',
    time: '08:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'gabinete',
    notes: '',
    contactPerson: '',
    participants: 'ANDRE PEDROSO',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'VISITA NA ESCOLA EURICO DE MORAES',
    date: '2025-05-14',
    time: '15:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'ESCOLA NO BAIRRO HALLER',
    notes: '',
    contactPerson: '',
    participants: 'SECRETÁRIO CLEBERSON E SECRETÁRIA ANNE',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM O CONSELHO DE PROTEÇÃO DOS ANIMAIS',
    date: '2025-05-15',
    time: '14:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'NO GABINETE',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'ABERTURA DA SEMANA DO COMERCIO',
    date: '2025-05-16',
    time: '18:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'PRAÇA PINHEIRO MACHADO',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'LIVE SEC. DA FAZENDA C/SR. BRUNO HESSE',
    date: '2025-05-12',
    time: '18:30',
    assignedTo: PREFEITO_USER_ID,
    location: 'no GAB',
    notes: '',
    contactPerson: '',
    participants: 'Sr. Nívio; Sr. Bruno',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'FESTA PADROEIRA NO INTERIOR OLHOS D"ÁGUA',
    date: '2025-05-18',
    time: '12:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'olhos d\'água',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'REUNIÃO COM SECRETÁRIO FLÁVIO',
    date: '2025-05-14',
    time: '09:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'NO GABINETE',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM BELTRAME E ROGER SOBRE EMENDAS PARLAMENTARES',
    date: '2025-05-15',
    time: '17:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'NO GABINETE',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM CARLOS GROSS',
    date: '2025-05-21',
    time: '09:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'NO GABINETE',
    notes: '',
    contactPerson: '',
    participants: 'procurador Leandro e Bruno Hesse',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'REUNIÃO SOBRE O CADIN',
    date: '2025-05-14',
    time: '10:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'NO GABINETE',
    notes: '',
    contactPerson: '',
    participants: 'secretário Cleber , Iloide e Cleber da cultura',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'JANTAR OFICIAL DA ABERTURA DE COMEMORAÇÃO DOS 150 ANOS DA IMIGRAÇÃO POLONESA NO RS',
    date: '2025-05-24',
    time: '19:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'salão paroquial de Guarani da Missões',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'REUNIÃO DA AMM EM CERRO LARGO',
    date: '2025-05-23',
    time: '09:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'CERRO LARGO',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'REUNIÃO COM JOEL AUTUÁRIO DE POA',
    date: '2025-05-20',
    time: '09:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'NO GABINETE',
    notes: '',
    contactPerson: '',
    participants: 'BRUNO HESSE',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'ENCONTRO DOS PREFEITO',
    date: '2025-05-16',
    time: '14:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'Em CAIBATÉ',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM MAJOR ALDO DA BRIGADA MILITAR SOBRE OS CABEAMENTOS E CÂMERAS',
    date: '2025-05-21',
    time: '14:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'NO GABINETE',
    notes: '',
    contactPerson: 'carlos Kelm',
    participants: 'Rodrigo Flores',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'REUNIÃO COM VEREADOR LORENZO TONETTO',
    date: '2025-05-20',
    time: '14:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'NO GABINETE',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'REUNINÃO COM A DIRETORA DO PRESIDIO REGIONAL DE SANTO ÂNGELO',
    date: '2025-05-21',
    time: '15:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'GABINETE',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'ENTREGA DE MÁQUINAS NA SECRETARIA RURAL',
    date: '2025-05-16',
    time: '08:30',
    assignedTo: PREFEITO_USER_ID,
    location: 'secretaria',
    notes: '',
    contactPerson: '',
    participants: 'secretário juca',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'REUNIÃO COM A LEANDRA',
    date: '2025-05-10',
    time: '08:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'NO GABINETE',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'REUNIÃO COM CLEBERSON DO PLANEJAMENTO E REURB',
    date: '2025-05-16',
    time: '10:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'NO GABINETE',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'VISITA NO CENTRO DE ESPORTES NA FRENTE DA PROSSEGUR',
    date: '2025-05-21',
    time: '16:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'centro de esportes',
    notes: '',
    contactPerson: '',
    participants: 'secretário Edimilson',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'VISITA NA DRACO',
    date: '2025-05-19',
    time: '14:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'DRACO',
    notes: '',
    contactPerson: '',
    participants: 'secretária Leandra',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'RENIÃO COM ANDRE PEDROSO E BRUNO HESSE',
    date: '2025-05-19',
    time: '08:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'GABINETE',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: true,
  },
  {
    title: 'ALMOÇO NA CONSTRUTORA STILLER',
    date: '2025-05-24',
    time: '12:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'construtora stiller',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'COQUETEL INAUGURAÇÃO',
    date: '2025-05-22',
    time: '19:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'FELICE/SANTA ROSA (Av. Expedicionário Weber,2099)',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'REUNIÃO C/ROSEMERI (SEC. DESENVOLV.SOCIAL E CIDADANIA)',
    date: '2025-05-20',
    time: '08:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'no GAB',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: false,
  },
  {
    title: 'REUNIÃO DE ALINHAMENTO C/VEREADORES',
    date: '2025-05-19',
    time: '10:00',
    assignedTo: PREFEITO_USER_ID,
    location: 'no GAB',
    notes: '',
    contactPerson: '',
    participants: '',
    isShared: false,
    isCompleted: true,
  }
];
    
